# <font color='blue'>SME243</font>

## Exercícios Práticos Relacionados à Revisão de Álgebra Linear


In [0]:
import numpy as np
import matplotlib.pyplot as plt

### Exercício 1)

Construa uma transformação linear que leva vetores de $\mathbb{R}^5$ para o sub-espaço $S$ gerado pelos vetores $(1,1,1)$ e $(0,0,1)$ em $\mathbb{R}^3$. Como você pode verificar que a transformação obtida está realizando o mapeamento desejado?

### Solução

In [3]:
# a matriz que representa a transformacao deve ser 3x5
A = np.asarray([[1,1,1],[0,0,1],[2,2,3],[1,1,2],[1,1,2]]).T
print(A)

[[1 0 2 1 1]
 [1 0 2 1 1]
 [1 1 3 2 2]]


In [10]:
# teste de corretude

u_nucleo = np.cross(A[:,0],A[:,1])

for i in range(10):
  v = np.random.uniform(low=-1,high=1,size=(5,1))
  u = np.dot(A,v)
  print(np.dot(u_nucleo.T,A[:,0]),np.dot(u_nucleo.T,A[:,1]))


0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0
0 0


### Exercício 2) 
Considere a transformação linear dada pela matriz 
$$
\left(\begin{array}{ccccccc}
3 & 9 & 6 & 6 & 9 & 3 & 1\\
2 & 0 & 9 & 2 & 0 & 5 & 3\\
0 & 0 & 1 & 0 & 1 & 0 & 2
\end{array}\right)
$$

a) Qual a dimensão do núcleo da transformação?<br>
b) Encontre uma base para o espaço núcleo.<br>
c) Verifique que a base encontrada está gerando o espaço núcleo.

### Solução

In [14]:
B = np.asarray([[3, 9, 6, 6, 9, 3, 1],
                [2, 0, 9, 2, 0, 5, 3],
                [0, 0, 1 , 0, 1, 0, 2]])

# as linhas nao sao ortogonais
print(np.dot(B[0,:].T,B[1,:]),np.dot(B[0,:].T,B[2,:]),np.dot(B[1,:].T,B[2,:]))

print(np.linalg.det(B[:,[0,1,2]]))

# como existem 3 colunas L.I. a dimensao do espaco coluna é 3, portanto o espaco linha tambem tem dimensao 3
# logo o nucleo tem dimensao 4

90 17 15
-17.999999999999996


**Encontrando uma base para o espaço núcleo**




In [15]:
# encontrando uma base para o nucleo
base=np.zeros((7,4))

for i in range(4):       # [x0,x1,x2,1,0,0,0], [x0,x1,x2,0,1,0,0], [x0,x1,x2,0,0,1,0], [x0,x1,x2,0,0,0,1]
  x = np.zeros((7,1))
  x[i+3]=1
  x[2] = -x[4]-2*x[6]
  x[1] = 5/6*x[2]-1/3*x[3]-x[4]+1/2*x[5]+7/18*x[6]
  x[0] = -9/2*x[2]-x[3]-5/2*x[5]-3/2*x[6]
  base[:,i] = x[:,0]

print(base)

[[-1.          4.5        -2.5         7.5       ]
 [-0.33333333 -1.83333333  0.5        -1.27777778]
 [-0.         -1.         -0.         -2.        ]
 [ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [16]:
# Verificando que os vetores calculados estão no núcleo

for i in range(4):
  print(np.dot(B,base[:,i]))

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[-1.77635684e-15  0.00000000e+00  0.00000000e+00]


### Exercício 3)
Considere o conjunto de vetores dados como colunas da matriz $C$. 

a) Qual a dimensão do espaço coluna?<br>
b) Se a dimensão é $k$, encontre $k$ vetores ortogonais que geram o espaço coluna.

In [15]:
C = np.random.randint(0,10,size=(4,9))
#C[:,2:]=np.ones((4,1))
print(C)

[[8 1 8 3 3 0 9 2 3]
 [2 2 9 0 3 7 2 0 2]
 [1 4 8 6 1 1 6 9 0]
 [7 2 9 7 7 8 6 8 4]]


In [16]:
import scipy.linalg as spl

np.set_printoptions(precision=3)
P,L,U = spl.lu(C)
for i in U:
   print(i)

[8. 1. 8. 3. 3. 0. 9. 2. 3.]
[ 0.     3.875  7.     5.625  0.625  1.     4.875  8.75  -0.375]
[ 0.     0.     3.839 -3.29   1.968  6.548 -2.452 -4.452  1.419]
[ 0.     0.     0.     2.714  4.21   7.765 -3.311  3.672  1.496]


### Solução

In [4]:
import itertools

columns4x4 = itertools.combinations(range(C.shape[1]),4)
# print(list(columns4x4)[:7])

columnsLI = 0
for i in columns4x4:
  det = np.linalg.det(C[:,i])
  print(i)
  if (det!=0.0):
    print(det)
    columnsLI = i
    break

print(columnsLI)

# portanto o espaco coluna tem dimensao 4

(0, 1, 2, 3)
102.00000000000004
(0, 1, 2, 3)


In [0]:
# Encontrando os vetores ortogonais 

### Exercício 4)
Considere o conjunto de pontos $(x_i,y_i)$ definido no código abaixo. Encontre os coeficientes $\alpha_i$ do polinômio:
$$
P(x)=\alpha_0+\alpha_1x+\alpha_2x^2+\cdots+\alpha_5x^5
$$
tal que o erro
$$
E(\alpha)=\sum_i\|P(x_i)-y_i\|^2
$$
Seja o menor possível.

**Dica**: Converta em um problema de mínimos quadrados

In [0]:
n = 20
x = np.linspace(0,2,n)
y = np.random.normal(1.0,1.0,n)

plt.plot(x,y,'o-')

### Solução

Para cada ponto $(x_i,y_i)$ temos:
$$
\begin{array}{c}
y_1\approx P(x_1)=\alpha_0+\alpha_1x_1+\alpha_2x_1^2+\alpha_3x_1^3+\alpha_4x_1^4+\alpha_5x_1^5\\
y_2\approx P(x_2)=\alpha_0+\alpha_1x_2+\alpha_2x_2^2+\alpha_3x_2^3+\alpha_4x_2^4+\alpha_5x_2^5\\
\vdots\\
y_n\approx P(x_n)=\alpha_0+\alpha_1x_n+\alpha_2x_n^2+\alpha_3x_n^3+\alpha_4x_n^4+\alpha_5x_n^5\\
\end{array}
$$

Escrevendo na forma matricial:
$$
\left[\begin{array}{c}
y_0\\
y_1\\
y_2\\
\vdots\\
y_n
\end{array}\right]\approx
\left[\begin{array}{cccccc}
1 & x_1 & x_1^2 & x_1^3 & x_1^4 & x_1^5\\
1 & x_2 & x_2^2 & x_2^3 & x_2^4 & x_2^5\\
  &     &       &  \vdots & & \\
1 & x_n & x_n^2 & x_n^3 & x_n^4 & x_n^5
\end{array}\right]
\left[\begin{array}{c}
\alpha_0\\
\alpha_1\\
\alpha_2\\
\vdots\\
\alpha_n
\end{array}\right]\\
\Downarrow\\
y\approx A\alpha
$$
A solução de menor erro é dada pela equação normal:
$$
A^\top A\alpha=A^\top y
$$

### Exercício 5)
Considere a forma quadrática abaixo:
$$
f(x,y,z)=x^2+3y^2+z^2-2xy+xz+3yz
$$
Verifique se a forma quadrática é definida positiva.

### Solução

Sabemos que toda forma quadrática pode ser escrita como:
$$
x^{\top}Ax = \sum_{i\leq j}a_{ij}x_ix_j
$$
Assim, a forma quadrática acima se torna $(x=x_1,y=x_2,z=x_3)$
$$
f(x_1,x_2,x_3)=
\left[\begin{array}{ccc}
x_1 & x_2 & x_3
\end{array}\right]
\left[\begin{array}{ccc}
1 & -1 & \frac{1}{2}\\
-1 & 3 & \frac{3}{2}\\
\frac{1}{2} & \frac{3}{2} & 1
\end{array}\right]
\left[\begin{array}{c}
x_1 \\ x_2 \\ x_3
\end{array}\right]
$$